channels:
  - conda-forge
  - https://conda.anaconda.org/conda-forge
  - defaults
dependencies:
  - conda-tree
  - ipycytoscape>=1.0.3
  - jupyterlab=3
  - matplotlib-base
  - networkx
  - pandas
  - traitlets
  - spectate
  - ipyvolume
